### ISSUE TITLE
sell to grid (still) has a to high priority, the charging of the batteries is oscillating

### ISSUE THREAD

**Issue by Edrettikketet** [victronenergy/dynamic-ess#127]
This issue is a continuation of issue #115.
![ESS settings](https://github.com/victronenergy/dynamic-ess/assets/132836191/864b8c9e-0636-4871-9cf5-987beb5fb6e7)
![66% load schedule](https://github.com/victronenergy/dynamic-ess/assets/132836191/f0ef13cd-80b3-4c4d-84bb-6e03c3fccebd)
![67% loadschedule](https://github.com/victronenergy/dynamic-ess/assets/132836191/b23551e1-0e8c-44f8-8c42-6d8bfe18e977)
![VRM scheme](https://github.com/victronenergy/dynamic-ess/assets/132836191/51553755-b2cc-45ee-9381-b3622829cb45)

My SOC is set to 65%.
When the sun comes out, the MPPT starts loading the batteries until it is 67%.  Then it starts to push solar and battery power into the grid. When the charge level is back to 65% it starts loading the batteries again.  This all happens in the same hour (same sell price of the current and the dynamic ESS node is updated to 0.1.14).

It starts oscillating within the 2%.  How?

**Comment by dirkjanfaber** [comment]
Did you import the new flow that adds the strategies and restrictions? Can you provide your site id?

**Comment by Edrettikketet** [comment]
102c6b644cfd

**Comment by dirkjanfaber** [comment]
I see that you are running firmware 3.21. Please use the latest beta feed for the strategies and restrictions to function.

You can switch via the remote console to this: _Settings -> Firmware -> Online updates -> Update feed_.

**Comment by Edrettikketet** [comment]
This doesn't make a difference.  The batteries are uncharging again at 67%.
![uncharging again](https://github.com/victronenergy/dynamic-ess/assets/132836191/20328dc8-82ea-404e-b279-8de1faaa6607)

**Comment by dirkjanfaber** [comment]
You still need to import the latest flow: https://github.com/victronenergy/dynamic-ess/blob/main/examples/fetch-dynamic-ess.json

Or do that from Node-RED:
![image](https://github.com/victronenergy/dynamic-ess/assets/3098947/07220a1a-eb71-4941-b08a-a8598169d60c)

**Comment by AbelLykens** [comment]
![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/515617f1-1c9a-4c58-bb10-6b89cbfcd6ad)
I tried importing into a new flow, I got this error. Any thoughts?

I would really like some UPGRADING.md, because I have not used NR before and this is all new for me.

**Comment by dirkjanfaber** [comment]
You need to install `node-red-dashboard` first, which you can do from the palette manager. I overlooked the need for that.

**Comment by dirkjanfaber** [comment]
I've updated the [README](https://github.com/victronenergy/dynamic-ess/blob/main/README.md#error-message-when-importing-imported-unrecognised-types-ui_template-ui_group-and-ui_tab) to handle this. Btw the VRM implementation is really comparable to the Node-RED implementation. If you want to go for the more user friendly approach, I'd advice to go that route. You can read about that on https://community.victronenergy.com/articles/256073/dynamic-ess-on-beta-vrm-part-4.html

**Comment by AbelLykens** [comment]
Thanks, that is a step in the right direction. After installing `node-red-dashboard` I still get:
> Flows stopped due to missing node types.
>    ui_template

![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/724172d5-dc05-4997-9533-741a8d7b7c09)

I did this, first install node-red-dashboard.
![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/822d8a54-2c1b-4db5-bf71-381ebb01af2e)

Then I deleted the existing flow, then re-imported. Seems broken [?].

**Comment by dirkjanfaber** [comment]
That `MODULE_NOT_FOUND` is unexpected. It looks like `node-red-dashboard` did not install properly. 

You can safely delete that `unkown: ui_template` node. But this is a bit strange.

**Comment by Edrettikketet** [comment]
I have exactly the same problem.  How to remove these nodes and reinstall them again?

**Comment by dirkjanfaber** [comment]
A click on the node, hitting the backspace button and deploying should be sufficient.

**Comment by AbelLykens** [comment]
A restart seems to be required after installing `node-red-dashboard`. It now works here.

**Comment by AbelLykens** [comment]
Wait no it does not:
![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/93854ace-3271-464c-940d-f796d097c37c)
But the flow now runs...

**Comment by dirkjanfaber** [comment]
Can you click on the box left from the "Enable Dynamic ESS (mode: Node-RED)" inject node?
![image](https://github.com/victronenergy/dynamic-ess/assets/3098947/56f0c045-7b2f-45a6-91ed-ea5b549467bb)
There should be a `4` below both orange nodes.

**Comment by Edrettikketet** [comment]
> That `MODULE_NOT_FOUND` is unexpected. It looks like `node-red-dashboard` did not install properly.
> 
> You can safely delete that `unkown: ui_template` node. But this is a bit strange.

How can we correct this? Is there a way to delete these nodes and reload them?

**Comment by dirkjanfaber** [comment]
I see that you have remote support enabled. If you don't mind, I can fix it remotely for you. Alternative is that you wait another day until I've finished describing on how to do it yourself.

**Comment by Edrettikketet** [comment]
You may do it, but I always like to know how I can do it myself.  So you may also describe it tomorrow. (I have some patience ;-)

**Comment by dirkjanfaber** [comment]
It turns out that it was just a matter of restarting Node-RED. No more "MODULE_NOT_FOUND" messages. It was less work that I had in mind to describe.

However I will describe the more thorough method [here](https://www.victronenergy.com/media/pg/Cerbo-S_GX/en/reset-to-factory-defaults-procedure.html) tomorrow.

**Comment by dirkjanfaber** [comment]
You are welcome. Happy to help. 

You probably already know, but on https://community.victronenergy.com/ there are also a lot of knowledgeable and helpful people for all Victron products. In case of trouble, that is also an excellent place to ask questions.

I'll close this issue now as it has derailed a bit from the original problem. And, with the updates, I am fairly sure it has been resolved. If you still encounter the problem, just open a new issue.

**Comment by Edrettikketet** [comment]
This comment was closed, but after updating as recommended the problem still persist.  The system is still oscillating between 55% (SoC) and 57% battery charge percentage.
